version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: crisp_postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crisp_db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  mqtt:
    image: emqx/emqx:5.8.3
    container_name: crisp_emqx
    restart: always
    environment:
      - EMQX_ALLOW_ANONYMOUS=true
    ports:
      - "1883:1883"
      - "18083:18083"
    volumes:
      - ./emqx_data:/opt/emqx/data